import * as fs from 'fs';

/**
 * @class LvDriversConfigGenerator
 * @brief Utility class for generating lv_drivers configuration files for LVGL v8.
 *
 * @description
 * This class generates the lv_drv_conf.h configuration file needed by the lv_drivers
 * repository when working with LVGL v8. LVGL v9 has built-in drivers and doesn't need this.
 */
export class LvDriversConfigGenerator {
	/**
	 * @brief Generates lv_drv_conf.h configuration file for SDL driver.
	 *
	 * Enables the SDL driver and configures display resolution. All other drivers
	 * (fbdev, evdev, monitors, etc.) are disabled since we only need SDL for Emscripten.
	 *
	 * @param outputPath Path where the lv_drv_conf.h file should be written.
	 * @param displayWidth Horizontal resolution for the SDL window.
	 * @param displayHeight Vertical resolution for the SDL window.
	 */
	public static generateLvDrvConf(outputPath: string, displayWidth: number, displayHeight: number): void {
		const config = `
/**
 * @file lv_drv_conf.h
 * Configuration file for lv_drivers – Generated by LVGL Live Preview
 */

#ifndef LV_DRV_CONF_H
#define LV_DRV_CONF_H

#include "lv_conf.h"

/*********************
 * DELAY INTERFACE
 *********************/
#define LV_DRV_DELAY_INCLUDE  <stdint.h>
#define LV_DRV_DELAY_US(us)  /*delay_us(us)*/       /*Delay the given number of microseconds*/
#define LV_DRV_DELAY_MS(ms)  /*delay_ms(ms)*/       /*Delay the given number of milliseconds*/

/*********************
 * DISPLAY INTERFACE
 *********************/

/*------------
 *  Common
 *------------*/
#define LV_DRV_DISP_INCLUDE         <stdint.h>           /*Dummy include by default*/
#define LV_DRV_DISP_CMD_DATA(val)  /*pin_x_set(val)*/    /*Set the command/data pin to 'val'*/
#define LV_DRV_DISP_RST(val)       /*pin_x_set(val)*/    /*Set the reset pin to 'val'*/

/*---------
 *  SPI
 *---------*/
#define LV_DRV_DISP_SPI_CS(val)          /*spi_cs_set(val)*/     /*Set the SPI's Chip select to 'val'*/
#define LV_DRV_DISP_SPI_WR_BYTE(data)    /*spi_wr(data)*/        /*Write a byte the SPI bus*/
#define LV_DRV_DISP_SPI_WR_ARRAY(adr, n) /*spi_wr_mem(adr, n)*/  /*Write 'n' bytes to SPI bus from 'adr'*/

/*------------------
 *  Parallel port
 *-----------------*/
#define LV_DRV_DISP_PAR_CS(val)          /*par_cs_set(val)*/  /*Set the Parallel port's Chip select to 'val'*/
#define LV_DRV_DISP_PAR_SLOW             /*par_slow()*/        /*Set low speed on the parallel port*/
#define LV_DRV_DISP_PAR_FAST             /*par_fast()*/        /*Set high speed on the parallel port*/
#define LV_DRV_DISP_PAR_WR_WORD(data)    /*par_wr(data)*/      /*Write a word to the parallel port*/
#define LV_DRV_DISP_PAR_WR_ARRAY(adr, n) /*par_wr_mem(adr,n)*/ /*Write 'n' bytes to Parallel ports from 'adr'*/

/***************************
 * INPUT DEVICE INTERFACE
 ***************************/

/*----------
 *  Common
 *----------*/
#define LV_DRV_INDEV_INCLUDE     <stdint.h>             /*Dummy include by default*/
#define LV_DRV_INDEV_RST(val)    /*pin_x_set(val)*/     /*Set the reset pin to 'val'*/
#define LV_DRV_INDEV_IRQ_READ    0 /*pn_x_read()*/      /*Read the IRQ pin*/

/*---------
 *  SPI
 *---------*/
#define LV_DRV_INDEV_SPI_CS(val)            /*spi_cs_set(val)*/     /*Set the SPI's Chip select to 'val'*/
#define LV_DRV_INDEV_SPI_MOSI(val)          /*spi_mosi_set(val)*/   /*Set the SPI's MOSI pin to 'val'*/
#define LV_DRV_INDEV_SPI_CLK(val)           /*spi_clk_set(val)*/    /*Set the SPI's CLK pin to 'val'*/
#define LV_DRV_INDEV_SPI_MISO                0 /*spi_miso_get()*/   /*Read the SPI's MISO pin*/

/*---------
 *  I2C
 *---------*/
#define LV_DRV_INDEV_I2C_START               /*i2c_start()*/       /*Make an I2C start*/
#define LV_DRV_INDEV_I2C_STOP                /*i2c_stop()*/        /*Make an I2C stop*/
#define LV_DRV_INDEV_I2C_RESTART             /*i2c_restart()*/     /*Make an I2C restart*/
#define LV_DRV_INDEV_I2C_WR(data)            /*i2c_wr(data)*/      /*Write a byte to the I1C bus*/
#define LV_DRV_INDEV_I2C_READ(last_read)     0 /*i2c_rd()*/        /*Read a byte from the I2C bud*/

/*********************
 *  DISPLAY DRIVERS
 *********************/

/*-------------------
 *  SDL
 *-------------------*/

/* Disable HiDPI support to prevent quarter-size rendering on macOS Retina displays.
 * Without this, SDL_WINDOW_ALLOW_HIGHDPI creates a 2x drawable size but the texture
 * remains at logical size, causing content to render in the upper-left quarter.
 * This results in slightly blurry rendering on Retina displays but ensures correct
 * display size. Windows and Linux are unaffected as they don't use HiDPI by default. */
#ifndef SDL_HIGHDPI
# define SDL_HIGHDPI 0
#endif

/* SDL based drivers for display, mouse, mousewheel and keyboard */
#ifndef USE_SDL
# define USE_SDL 1
#endif

/* Hardware accelerated SDL driver */
#ifndef USE_SDL_GPU
# define USE_SDL_GPU 0
#endif

#if USE_SDL || USE_SDL_GPU
# define SDL_HOR_RES     ${displayWidth}
# define SDL_VER_RES     ${displayHeight}
# define SDL_ZOOM        1
# define SDL_INCLUDE_PATH    <SDL2/SDL.h>

/* Use window without borders */
# define SDL_FULLSCREEN 0

/* Window will be resized when resolution is changed at runtime */
# define SDL_RESOLUTION_AUTO_DETECT 1

/* Use double buffering with SDL (not compatible with SDL_FULLSCREEN) */
# define SDL_DOUBLE_BUFFERED 0

/* Open two windows to test multi-display support */
# define SDL_DUAL_DISPLAY 0

/* Set the window title */
# define SDL_WINDOW_TITLE "LVGL Preview"
#endif

/*-------------------
 *  Monitor of PC
 *-------------------*/

#ifndef USE_MONITOR
# define USE_MONITOR 0
#endif

/*-----------------------------------
 *  Native Windows (including mouse)
 *----------------------------------*/

#ifndef USE_WIN32DRV
# define USE_WIN32DRV 0
#endif

/*-----------------------------------
 *  GTK drivers (including mouse)
 *----------------------------------*/

#ifndef USE_GTK
# define USE_GTK 0
#endif

/*-----------------------------------
 *  WAYLAND drivers (including mouse)
 *----------------------------------*/

#ifndef USE_WAYLAND
# define USE_WAYLAND 0
#endif

/*-------------------------------
 *  X11 drivers (including mouse)
 *------------------------------*/

#ifndef USE_X11
# define USE_X11 0
#endif

/*----------------
 *  SSD1963
 *----------------*/

#ifndef USE_SSD1963
# define USE_SSD1963 0
#endif

/*----------------
 *  ST7565
 *----------------*/

#ifndef USE_ST7565
# define USE_ST7565 0
#endif

/*-----------------
 *  GC9A01
 *-----------------*/

#ifndef USE_GC9A01
# define USE_GC9A01 0
#endif

/*-----------------
 *  UC1610
 *-----------------*/

#ifndef USE_UC1610
# define USE_UC1610 0
#endif

/*-----------------
 *  SHARP memory in pixel
 *-----------------*/

#ifndef USE_SHARP_MIP
# define USE_SHARP_MIP 0
#endif

/*-----------------
 *  ILI9341
 *-----------------*/

#ifndef USE_ILI9341
# define USE_ILI9341 0
#endif

/*-------------------
 *  Linux frame buffer
 *-------------------*/

#ifndef USE_FBDEV
# define USE_FBDEV 0
#endif

/*-------------------
 *  DRM
 *-------------------*/

#ifndef USE_DRM
# define USE_DRM 0
#endif

/*********************
 *  INPUT DEVICES
 *********************/

/*--------------
 *  XPT2046
 *--------------*/

#ifndef USE_XPT2046
# define USE_XPT2046 0
#endif

/*-----------------
 *  FT5406EE8
 *-----------------*/

#ifndef USE_FT5406EE8
# define USE_FT5406EE8 0
#endif

/*-------------------------------
 *  Mouse or touchpad on PC (using SDL)
 *------------------------------*/

/* This is handled by USE_SDL */

/*-------------------------------
 *  Mousewheel on PC (using SDL)
 *------------------------------*/

/* This is handled by USE_SDL */

/*-------------------------------
 *  Touchscreen on Linux (using evdev)
 *------------------------------*/

#ifndef USE_EVDEV
# define USE_EVDEV 0
#endif

/*-------------------------------
 *  Mouse or touchpad on Linux (using libinput)
 *------------------------------*/

#ifndef USE_LIBINPUT
# define USE_LIBINPUT 0
#endif

/*-------------------------------
 *  Mouse or touchpad on Linux (using BSD)
 *------------------------------*/

#ifndef USE_BSD_EVDEV
# define USE_BSD_EVDEV 0
#endif

/*------------------
 *  Keyboard on PC (using SDL)
 *------------------*/

/* This is handled by USE_SDL */

/*-------------------------------
 *  Keypad on Linux (using evdev)
 *------------------------------*/

/* This is handled by USE_EVDEV */

/*-------------------------------
 *  Encoder on PC (using SDL)
 *------------------------------*/

/* This is handled by USE_SDL */

/*-------------------------------
 *  Button on PC (using SDL)
 *------------------------------*/

/* This is handled by USE_SDL */

#endif /* LV_DRV_CONF_H */
`;

		fs.writeFileSync(outputPath, config);
	}
}
